name: DBT CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'


      - name: Install DBT and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres

      - name: Run DBT Debug
        env:
          DBT_PROFILES_DIR: ./dbt
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_PORT: ${{ secrets.DBT_PORT }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
        run: |
          dbt debug --project-dir ./dbt/ecommerce

      - name: Run DBT Build
        env:
          DBT_PROFILES_DIR: ./dbt
        run: |
          dbt deps --project-dir ./dbt/ecommerce
          dbt test --project-dir ./dbt/ecommerce
          dbt build --project-dir ./dbt/ecommerce
